name: Deploy FastAPI Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name fastapi-app fastapi-app

      - name: Check if FastAPI is running
        run: |
          sleep 10  # Wait for the container to start
          curl -X GET "http://localhost:8000/" -H "accept: application/json"

      - name: Stop Docker container
        run: |
          docker stop fastapi-app
          docker rm fastapi-app

      - name: Upload Docker image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/fastapi-app:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
